CREATE TABLE "preprocessed_recommendations_by_product" (
    id bigint NOT NULL,
    product_id TEXT NOT NULL,
    buy_with_product_id TEXT NOT NULL,
    WEIGHT INTEGER NOT NULL,
    date_created timestamp without time zone NOT NULL DEFAULT now(),
    last_updated timestamp without time zone NOT NULL DEFAULT now()
);

ALTER TABLE "preprocessed_recommendations_by_product" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "preprocessed_recommendations_by_product_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
    );

ALTER TABLE "preprocessed_recommendations_by_product"
    ADD CONSTRAINT "preprocessed_recommendations_by_product_pkey" PRIMARY KEY (id);
