micronaut:
  application:
    name: 'klevuDataRecommendation'
  server:
    port: 8082
datasources:
  default:
    url: ${DATASOURCE_URL:jdbc:postgresql://127.0.0.1:5432/klevu}
    driverClassName: 'org.postgresql.Driver'
    username: 'postgres'
    password: ''

data:
  file: 'selected-data.txt'

jpa:
  default:
    entity-scan:
      packages: 'com.klevu.task.model'
    packages-to-scan:
      - 'com.klevu.task.model'
    properties:
      hibernate:
        bytecode:
          provider: none
        show_sql: true


recommendation:
  limit: 5

flyway:
  datasources:
    default:
      enabled: true
      locations:
        - classpath:databasemigrations